language: node_js
node_js:
  - "8"
  - "9"

jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: skip
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
